apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyfyihb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyfyihb
  template:
    metadata:
      labels:
        app: tyfyihb
    spec:
      containers:
      - image: okteto.dev/tyfyihb:latest
        name: tyfyihb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "282d9888-fbfb-4e70-971e-59b8312e7d24"
        - name: Vless_Path
          value: "/vl5gkgfy8"
        - name: Vmess_UUID
          value: "282d9888-fbfb-4e70-971e-59b8312e7d24"
        - name: Vmess_Path
          value: "/vm6tui5sx"
        - name: Share_Path
          value: "/v2link"
